In [31]:
from __future__ import print_function
import matplotlib.pyplot as plt
import numpy as np
import time
import csv
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM, SimpleRNN
from keras.layers.wrappers import TimeDistributed
import argparse
from RNN_utils import *

DATA_DIR = './data/warpeace_input.txt'
BATCH_SIZE = 50
HIDDEN_DIM = 500
SEQ_LENGTH = 50
WEIGHTS = './checkpoints/warandpeace/checkpoint_layer_2_hidden_500_epoch_10.hdf5'

lossfile = './data/warpeace_loss.txt'
# start = args['start']
# randgen = args['randgen']

# GENERATE_LENGTH = args['generate_length']
LAYER_NUM = 2

# Creating training data
X, y, VOCAB_SIZE, ix_to_char, char_to_ix = load_data(DATA_DIR, SEQ_LENGTH)

# Creating and compiling the Network
model = Sequential()
model.add(LSTM(HIDDEN_DIM, input_shape=(None, VOCAB_SIZE), return_sequences=True))
for i in range(LAYER_NUM - 1):
  model.add(LSTM(HIDDEN_DIM, return_sequences=True))
model.add(TimeDistributed(Dense(VOCAB_SIZE)))
model.add(Activation('softmax'))
model.compile(loss="categorical_crossentropy", optimizer="rmsprop")

# Generate some sample before training to know how bad it is!
#print("\n\nGenerating untrained text...\n\n")
#generate_text(model, args['generate_length'], VOCAB_SIZE, ix_to_char, -1, 0)

if not WEIGHTS == '':
  model.load_weights(WEIGHTS)
#   nb_epoch = int(WEIGHTS[WEIGHTS.rfind('_') + 1:WEIGHTS.find('.')])


Data length: 3258246 characters
Vocabulary size: 87 characters


In [34]:
ix = [38]
ix

[38]

In [35]:
ix_to_char[ix[-1]]

'k'

In [36]:
X = np.zeros((1, 10, VOCAB_SIZE))

In [37]:
X[0, 0, :][ix[-1]] = 1
X

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [38]:
predict = model.predict(X[:, :1, :], batch_size=1)
predict

array([[[1.89361781e-01, 7.59935830e-08, 2.07896139e-02, 4.65660975e-07,
         5.30527764e-08, 2.40352051e-07, 2.46867309e-08, 1.88223446e-08,
         3.23492415e-08, 4.83214626e-06, 4.47581016e-07, 2.91105857e-06,
         3.52147964e-07, 1.58960393e-06, 1.19518031e-08, 1.29732274e-04,
         3.99584286e-02, 2.77540693e-03, 1.61357878e-08, 6.15607642e-05,
         1.16491494e-04, 1.98245175e-07, 1.74652577e-08, 1.61632627e-08,
         6.99982222e-04, 2.41519160e-08, 1.82782543e-07, 1.58407488e-07,
         6.95402850e-05, 2.96210172e-04, 2.96222424e-06, 3.09306597e-06,
         7.37251867e-07, 1.19923243e-06, 1.28744284e-06, 7.11110147e-07,
         1.24069018e-04, 6.24186723e-05, 2.44794028e-05, 4.34218086e-02,
         2.72726268e-02, 2.51962966e-03, 3.98209704e-13, 1.74976631e-05,
         2.99196117e-08, 1.96644550e-08, 1.23436982e-02, 2.54324732e-07,
         2.37929598e-07, 3.31264819e-05, 1.03737023e-06, 4.92664583e-07,
         1.00083341e-07, 3.02227409e-06, 2.76688638

In [39]:
ix = np.argmax(predict[0], 1)
ix
ix_to_char[ix[-1]]

'e'

In [40]:
X[0, 1, :][ix[-1]] = 1
X

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [41]:
predict = model.predict(X[:, :2, :], batch_size=1)
predict

array([[[1.89361721e-01, 7.59934551e-08, 2.07896009e-02, 4.65663277e-07,
         5.30532418e-08, 2.40351852e-07, 2.46868765e-08, 1.88223126e-08,
         3.23493090e-08, 4.83212398e-06, 4.47580618e-07, 2.91106448e-06,
         3.52147282e-07, 1.58960870e-06, 1.19517818e-08, 1.29732172e-04,
         3.99584100e-02, 2.77540600e-03, 1.61358216e-08, 6.15608878e-05,
         1.16491465e-04, 1.98244436e-07, 1.74653287e-08, 1.61632041e-08,
         6.99981349e-04, 2.41520119e-08, 1.82781875e-07, 1.58408412e-07,
         6.95402923e-05, 2.96209357e-04, 2.96222470e-06, 3.09306938e-06,
         7.37250502e-07, 1.19923698e-06, 1.28744307e-06, 7.11111568e-07,
         1.24069265e-04, 6.24184395e-05, 2.44793391e-05, 4.34218086e-02,
         2.72726212e-02, 2.51962873e-03, 3.98209758e-13, 1.74976994e-05,
         2.99195619e-08, 1.96644567e-08, 1.23436945e-02, 2.54324249e-07,
         2.37929626e-07, 3.31263545e-05, 1.03736636e-06, 4.92666061e-07,
         1.00083078e-07, 3.02227431e-06, 2.76689690